name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Deploy Project Artifacts to Vercel
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" ${{ steps.commit.outputs.short }}.sid86.me

  Update-Readme:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - name: '📥  Fetching Repository Contents'
        uses: actions/checkout@main
      - id: commit
        uses: prompt/actions-commit-hash@v3
      # Runs a set of commands using the runners shell
      - name: Update README.md
        run: |
          sed -i 's/<commithash>/'${{ steps.commit.outputs.short }} }}'/' README.md
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "Automated report"
          git push
