name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main

jobs:
  Update-Readme:
    name: Update Readme
    runs-on: ubuntu-latest
    # needs: Deploy-Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Generate README
        run: npm run generate:readme
      - name: Commit and push if changed
        run: |
          git config --global user.name 'sid86-dev'
          git config --global user.email '
          git add README.md
          git commit -m "Update README.md"
          git push
